name: challenge2

on: push

env:
  ARTIFACT_NAME: artifact

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: artifact upload
      uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: ./${{ env.ARTIFACT_NAME }}